# Generated by Django 5.1.5 on 2025-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_template_editable_json_template_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
    ]
