# Generated by Django 5.1.5 on 2025-02-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_template_image_height_template_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='template',
            name='image_width',
        ),
        migrations.AddField(
            model_name='template',
            name='canvas_height',
            field=models.IntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='template',
            name='canvas_width',
            field=models.IntegerField(default=1080),
        ),
    ]
