# Generated by Django 5.1.5 on 2025-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0006_alter_box_height_alter_box_width_alter_box_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='canvas_height',
            new_name='original_height',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='canvas_width',
            new_name='original_width',
        ),
        migrations.RemoveField(
            model_name='box',
            name='height',
        ),
        migrations.RemoveField(
            model_name='box',
            name='width',
        ),
        migrations.RemoveField(
            model_name='box',
            name='x',
        ),
        migrations.RemoveField(
            model_name='box',
            name='y',
        ),
        migrations.AddField(
            model_name='box',
            name='height_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='width_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='x_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='y_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='aspect_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name='TemplateEdit',
        ),
    ]
