# Generated by Django 5.1.5 on 2025-02-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0007_rename_canvas_height_template_original_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('edited_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='templates_app.template')),
            ],
        ),
    ]
